version: '3.8'

services:
  todo_service:
    build:
      context: ./todo_app
    ports:
      - "8000:8000"
    volumes:
      - todo_data:/app/data
    restart: always

  shorturl_service:
    build:
      context: ./shorturl_app
    ports:
      - "8001:8001"
    volumes:
      - shorturl_data:/app/data
    restart: always

volumes:
  todo_data:
  shorturl_data: