name: CI/CD for FastAPI Project

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Вход в Docker Hub через секреты
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и пуш todo_app
      - name: Build and push todo_app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo_app:latest ./todo_app
          docker push ${{ secrets.DOCKER_USERNAME }}/todo_app:latest

      # 4. Сборка и пуш shorturl_app
      - name: Build and push shorturl_app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shorturl_app:latest ./shorturl_app
          docker push ${{ secrets.DOCKER_USERNAME }}/shorturl_app:latest